#!/usr/bin/env ruby

require 'fileutils'
require 'colorize'

puts "\nConfirm takein? This will take in dotfiles and scripts from your current directories. [y/n]".green

approval = gets.chomp

@path_script_source = "/Users/Seiyial/SyxApps/Scripts"

abort if approval.downcase != 'y'
puts 'Migrate!'.green
FileUtils.copy_entry(@path_script_source,"./Scripts", remove_destination: true)
puts 'Scripts Migrated'
