#!/bin/bash

case "$1" in
  s|server|svr)
    echo "    💫  ⭐️  SHQ Server ⭐️  💫"
    bundle exec hanami server
    ;;
  db)
    cd ~/Syxworks/seiyianhq
    HANAMI_ENV=test bundle exec hanami db prepare && bundle exec hanami db prepare
    ;;
  "")
    echo "
    ⭐️  Welcome to Seiyian HQ ⭐️"
    ;;
  *)
    echo "
    ☔️  invalid command"
  ;;
esac