alias gpo='
echo "  🌄 $(tput setaf 39 && tput bold) Pulling Origin..." && tput sgr0 && tput setaf 39 && git pull origin'
alias gs='
echo "  🎇 $(tput setaf 39 && tput bold) Repo Status" && tput sgr0 && tput setaf 39 && git status'
alias gcc='
echo "  🎑 $(tput setaf 39 && tput bold) Full Commit" && tput sgr0 && tput setaf 39 && git add . && git commit -m'
alias gcca='git commit --amend'
alias cko='
echo "  🌃 $(tput setaf 39 && tput bold) △  Checkout △" && tput sgr0 && tput setaf 39 && git checkout'
alias gccp='
echo "  🌃 $(tput setaf 39 && tput bold) Push $(tput setaf 1 && git rev-parse --abbrev-ref HEAD) $(tput setaf 39)to Origin" && tput sgr0 && tput setaf 39 && git push origin'
alias gpod='
echo "  🌃 $(tput setaf 39 && tput bold) △  Checkout △" && tput sgr0 && tput setaf 39 && git checkout develop && echo "  🌄 $(tput setaf 39 && tput bold) Pulling Origin..." && tput sgr0 && tput setaf 39 && git pull origin develop'
alias gl='git log'
alias glp='git log -p'
alias gconvg='git rebase -i HEAD~2'
alias gbb='git rebase'
alias gqconv='
echo "  🌃 $(tput setaf 39) 💠  Git Branch Converge 💠" && git merge'
alias gll='git branch'
alias glld='git branch -d'
alias glllld='git branch -D'