#!/bin/bash

# Color
tput setaf 32

# MAIN
case "$1" in
  s|d)
    clear
    echo "   💎  ABO Desktop :: yarn run dev 💎"
    yarn run dev
    ;;
  yarninstall|yi)
    clear
    echo "   💎  ABO Desktop :: yarn install 💎"
    yarn install
    ;;
  yarntest|yarnt|yt|ytest)
    echo "   💎  ABO Desktop :: yarn test 💎"
    yarn test
    ;;
  pull|gpod|gpo|p)
    echo "   💎  ABO Desktop :: Pull Origin 💎"
    tput setaf 45
    git pull origin
    ;;
  "")
    echo "   💎  ABO Desktop 💎"
    ;;
  *)
    echo "
    ☔️  $(tput setaf 117)invalid command"
  ;;
esac

tput sgr0