#!/bin/bash

case "$1" in
  s|server|svr)
    echo "    💫  ⭐️  SHQ Server ⭐️  💫"
    iex -S mix phx.server
    ;;
  db)
    # cd ~/Syxworks/seiyianhq
    # HANAMI_ENV=test bundle exec hanami db prepare && bundle exec hanami db prepare
    ;;
  ss)
    mix phx.server
    ;;
  "")
    echo "
    ⭐️  Welcome to Seiyian HQ ⭐️"
    ;;
  *)
    echo "
    ☔️  invalid command"
  ;;
esac