#!/bin/bash

tput setaf 11
clear

case "$1" in
  i|install|deps)
    echo "
      💠  SeiyianHQ 💠  :: INSTALL
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  "
    mix deps.get
    ;;
  s|server|svr)
    echo "
      💠  SeiyianHQ 💠  :: SERVER
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  "
    iex -S mix phx.server
    ;;
  db|m|migrate)
    clear
    echo "
      💠  SeiyianHQ 💠  :: Mix Ecto.Migrate
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  "
    mix ecto.migrate
    ;;
  ss)
    clear
    echo "
      💠  SeiyianHQ 💠  :: SERVER (no-console)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  "
    mix phx.server
    ;;
  "")
    echo "
      💠  SHQ 💠     welcome!"
    ;;
  *)
    echo "
      💠  SHQ 💠
    ☔️  invalid command"
  ;;
esac