#!/bin/bash
NOW=`date +"%Y-%m-%d_T%H%M.%S"`
POWDER_BLUE=$(tput setaf 153)
LIME_YELLOW=$(tput setaf 190)
RESET=$(tput sgr0)
BOLD=$(tput bold)
RED=$(tput setaf 1)
NB=$(tput setaf 117) # niceblue
TEAL=$(tput setaf 30)
GREEN=$(tput setaf 40)
wait
printf "${RESET}${NB}\nCHAKRAWTH!!"
wait
heroku pg:pull DATABASE_URL liredb --remote lire
wait
printf "${GREEN}Done!! :) ✓${RESET}${NB}\n Have a nice day!!"
exit
